"""empty message

Revision ID: 41e9cb13d6aa
Revises: None
Create Date: 2015-09-07 20:36:23.327538

"""

# revision identifiers, used by Alembic.
revision = '41e9cb13d6aa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=256), nullable=True),
    sa.Column('client_secret', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    ### end Alembic commands ###
